language: elixir

sudo: false

elixir:
  - '1.6.5'

otp_release:
  - '20.0'

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix coveralls.html
  - mix credo
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps
