language: elixir

sudo: false

elixir:
  - '1.4.5'
  - '1.5.3'
  - '1.6.1'
  - '1.6.5'

otp_release:
  - '20.0'
  - '20.1'
  - '20.2'
  - '20.3'

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix coveralls.travis --max-cases 1
  - mix credo
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps
