language: elixir

sudo: false

elixir:
  - 1.8

otp_release:
  - 21.0

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix coveralls.html
  - mix credo
  - mix dialyzer --halt-exit-status
  - mix format --check-formatted --dry-run

cache:
  directories:
    - _build
    - deps
